---
collections:
  - name: mlowcher61.netskope
    version: ">=0.3.0"
  # To build the EE against unreleased changes instead, use the git source:
  # - name: https://github.com/mlowcher61/netskope.git
  #   type: git
  #   version: main
